import tensorflow as tf
import matplotlib.pyplot as plt
import pickle
from model import *

#importing the VAE
pkl_file = open('model.pkl', 'rb')
VAE_imp = pickle.load(pkl_file)
pkl_file.close()

rnd_mean_var = tf.random.normal((100, 2), 0, 1).numpy() #100 random vectors generated by normal distribution

generated_images = VAE_imp.decoder(rnd_mean_var) #decoding these random vectors

#plotting the generated images
fig, axs = plt.subplots(10, 10, figsize=(50, 50))
for i in range(10):
    for j in range(10):
        axs[i][j].set_title('mean: {mean}\nvar: {var}'.format(mean=rnd_mean_var[i*10+j][0], var=rnd_mean_var[i*10+j][1]))
        axs[i][j].imshow(generated_images[i*10+j], cmap='gray')